[package]
name = "produce"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish = false

[dependencies]
fluvio = { version = "0.15.2" }
async-std = { version = "1.8.0", default-features = false, features = ["attributes"] }
